name: PDF Load Test

on:
  workflow_dispatch:

jobs:
  load_test_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Load test PDF with curl in parallel
        run: |
          export URL="https://canada-first-for-a-change.s3.us-west-2.amazonaws.com/20250418_CPCPlatform_8-5x11_EN_R1-pages.pdf"
          while true
          do
            for i in {1..100}; do
              curl -s -o /dev/null -w "%{http_code}\n" "$URL" &
              sleep 0.1
            done
          done
          wait
